default: &default
  adapter: oracle_enhanced
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= Rails.application.credentials.sitafe[:host] %>
  username: <%= Rails.application.credentials.sitafe[:username] %>
  password: <%= Rails.application.credentials.sitafe[:password] %>

#--------------------------------------------------
# default: &default
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

# development:
#   <<: *default
#   database: db/development.sqlite3